version: '2.3'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-dataset:/var/lib/postgresql/data
    networks:
      - db_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: favourite_recipes

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - postgres
    ports:
      - "9090:80"
    networks:
      - db_network  
    environment:
      PGADMIN_DEFAULT_EMAIL: abubakar.cs@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root

networks:
    db_network:
      driver: bridge
      name: postgres_db_network
    
volumes:
  pg-dataset: